// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
float Time;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    float t= Time % 2.0f;
    float checker = (id.x / 8 + id.y / 8) % 2 * t;
    Result[id.xy] = float4(checker, checker, checker, 1.0);
}
